extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - test
      - refactor
      - perf
      - chore
      - ci
  # Allow sentence-case for Dependabot commits (e.g. "chore(deps): Bump ...")
  subject-case:
    - 0
